export const pointDistributions = {
  _: 0,
  a: 1,
  b: 3,
  c: 3,
  d: 2,
  e: 1,
  f: 4,
  g: 2,
  h: 4,
  i: 1,
  j: 8,
  k: 5,
  l: 1,
  m: 3,
  n: 1,
  o: 1,
  p: 3,
  q: 10,
  r: 1,
  s: 1,
  t: 1,
  u: 1,
  v: 4,
  w: 4,
  x: 8,
  y: 4,
  z: 10,
}

export const letterDistribution = {
  _: 2,
  a: 9,
  b: 2,
  c: 2,
  d: 4,
  e: 12,
  f: 2,
  g: 3,
  h: 2,
  i: 9,
  j: 1,
  k: 1,
  l: 4,
  m: 2,
  n: 6,
  o: 8,
  p: 2,
  q: 1,
  r: 6,
  s: 4,
  t: 6,
  u: 4,
  v: 2,
  w: 2,
  x: 1,
  y: 2,
  z: 1,
}

// left to right is a-o
// top to bottom is 1-15
const bonuses = [
  { multiplier: 3, type: 'word', position: '' },
  { multiplier: 3, type: 'word', position: '' },
  { multiplier: 3, type: 'word', position: '' },
  { multiplier: 3, type: 'word', position: '' },
  { multiplier: 3, type: 'word', position: '' },
  { multiplier: 3, type: 'word', position: '' },
  { multiplier: 3, type: 'word', position: '' },
  { multiplier: 3, type: 'word', position: '' },

  { multiplier: 2, type: 'word', position: '' },
  { multiplier: 2, type: 'word', position: '' },
  { multiplier: 2, type: 'word', position: '' },
  { multiplier: 2, type: 'word', position: '' },
  { multiplier: 2, type: 'word', position: '' },
  { multiplier: 2, type: 'word', position: '' },
  { multiplier: 2, type: 'word', position: '' },
  { multiplier: 2, type: 'word', position: '' },
  { multiplier: 2, type: 'word', position: '' },
  { multiplier: 2, type: 'word', position: '' },
  { multiplier: 2, type: 'word', position: '' },
  { multiplier: 2, type: 'word', position: '' },
  { multiplier: 2, type: 'word', position: '' },
  { multiplier: 2, type: 'word', position: '' },
  { multiplier: 2, type: 'word', position: '' },
  { multiplier: 2, type: 'word', position: '' },

  { multiplier: 3, type: 'letter', position: '' },
  { multiplier: 3, type: 'letter', position: '' },
  { multiplier: 3, type: 'letter', position: '' },
  { multiplier: 3, type: 'letter', position: '' },
  { multiplier: 3, type: 'letter', position: '' },
  { multiplier: 3, type: 'letter', position: '' },
  { multiplier: 3, type: 'letter', position: '' },
  { multiplier: 3, type: 'letter', position: '' },
  { multiplier: 3, type: 'letter', position: '' },
  { multiplier: 3, type: 'letter', position: '' },
  { multiplier: 3, type: 'letter', position: '' },
  { multiplier: 3, type: 'letter', position: '' },

  { multiplier: 2, type: 'letter', position: '' },
  { multiplier: 2, type: 'letter', position: '' },
  { multiplier: 2, type: 'letter', position: '' },
  { multiplier: 2, type: 'letter', position: '' },
  { multiplier: 2, type: 'letter', position: '' },
  { multiplier: 2, type: 'letter', position: '' },
  { multiplier: 2, type: 'letter', position: '' },
  { multiplier: 2, type: 'letter', position: '' },
  { multiplier: 2, type: 'letter', position: '' },
  { multiplier: 2, type: 'letter', position: '' },
  { multiplier: 2, type: 'letter', position: '' },
  { multiplier: 2, type: 'letter', position: '' },
  { multiplier: 2, type: 'letter', position: '' },
  { multiplier: 2, type: 'letter', position: '' },
  { multiplier: 2, type: 'letter', position: '' },
  { multiplier: 2, type: 'letter', position: '' },
  { multiplier: 2, type: 'letter', position: '' },
  { multiplier: 2, type: 'letter', position: '' },
  { multiplier: 2, type: 'letter', position: '' },
  { multiplier: 2, type: 'letter', position: '' },
  { multiplier: 2, type: 'letter', position: '' },
  { multiplier: 2, type: 'letter', position: '' },
  { multiplier: 2, type: 'letter', position: '' },
  { multiplier: 2, type: 'letter', position: '' },
]

const bonusMap = [
  [`3w  2l   3w   2l  3w`],
  [` 2w   3l   3l   2w `],
  [`  2w   2l 2l   2w  `],
  [`2l  2w   2l   2w  2l`],
  [`    2w     2w    `],
  [` 3l   3l   3l   3l `],
  [`  2l   2l 2l   2l  `],
  [`3w  2l       2l  3w`],
  [`  2l   2l 2l   2l  `],
  [` 3l   3l   3l   3l `],
  [`    2w     2w    `],
  [`2l  2w   2l   2w  2l`],
  [`  2w   2l 2l   2w  `],
  [` 2w   3l   3l   2w `],
  [`3w  2l   3w   2l  3w`],
]

export const editedBonusMap = [
  [
    { value: '3w' },
    { value: '' },
    { value: '' },
    { value: '2l' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '3w' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '2l' },
    { value: '' },
    { value: '' },
    { value: '3w' },
  ],
  [
    { value: '' },
    { value: '2w' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '3l' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '3l' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '2w' },
    { value: '' },
  ],
  [
    { value: '' },
    { value: '' },
    { value: '2w' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '2l' },
    { value: '' },
    { value: '2l' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '2w' },
    { value: '' },
    { value: '' },
  ],
  [
    { value: '2l' },
    { value: '' },
    { value: '' },
    { value: '2w' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '2l' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '2w' },
    { value: '' },
    { value: '' },
    { value: '2l' },
  ],
  [
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '2w' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '2w' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
  ],
  [
    { value: '' },
    { value: '3l' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '3l' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '3l' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '3l' },
    { value: '' },
  ],
  [
    { value: '' },
    { value: '' },
    { value: '2l' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '2l' },
    { value: '' },
    { value: '2l' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '2l' },
    { value: '' },
    { value: '' },
  ],
  [
    { value: '3w' },
    { value: '' },
    { value: '' },
    { value: '2l' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '2l' },
    { value: '' },
    { value: '' },
    { value: '3w' },
  ],
  [
    { value: '' },
    { value: '' },
    { value: '2l' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '2l' },
    { value: '' },
    { value: '2l' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '2l' },
    { value: '' },
    { value: '' },
  ],
  [
    { value: '' },
    { value: '3l' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '3l' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '3l' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '3l' },
    { value: '' },
  ],
  [
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '2w' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '2w' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
  ],
  [
    { value: '2l' },
    { value: '' },
    { value: '' },
    { value: '2w' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '2l' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '2w' },
    { value: '' },
    { value: '' },
    { value: '2l' },
  ],
  [
    { value: '' },
    { value: '' },
    { value: '2w' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '2l' },
    { value: '' },
    { value: '2l' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '2w' },
    { value: '' },
    { value: '' },
  ],
  [
    { value: '' },
    { value: '2w' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '3l' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '3l' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '2w' },
    { value: '' },
  ],
  [
    { value: '3w' },
    { value: '' },
    { value: '' },
    { value: '2l' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '3w' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '2l' },
    { value: '' },
    { value: '' },
    { value: '3w' },
  ],
]

const emptyBoard = [
  [
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
  ],
  [
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
  ],
  [
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
  ],
  [
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
  ],
  [
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
  ],
  [
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
  ],
  [
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
  ],
  [
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
  ],
  [
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
  ],
  [
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
  ],
  [
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
  ],
  [
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
  ],
  [
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
  ],
  [
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
  ],
  [
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
